### ISSUE TITLE
is it passible to be HA?

### ISSUE THREAD

**Issue by NietzscheX** [gaurav-gupta-gtm/ansible-kubeadm#1]
thanks for your sharing.
i follow your guid,and fix some myself error ( eg. can't connect to google.com),and change copy join command to local as follow,or it will occur some priviate error.
```
 #cat fetch_join_url.yml                                                                                                                                      main b00939b ✗
- name: fetch the join command
  shell: kubeadm token create --print-join-command
  register: join

- name: copy join command to localhost(ansible master)
  become: no
  delegate_to: localhost
  copy:
    content: "{{ join.stdout }}"
    dest: "{{ dest_path }}"
    mode: 0777
```

i wander is it possible to build a HA cluster?
this time i have ONE master,Two Nodes.  if i want to add more two MASTER as HA...thanks for your help.
